### ISSUE TITLE
Error: The terraform-provider-maas_v3.1.3 plugin crashed!

### ISSUE THREAD

**Issue by pchandra19** [canonical/terraform-provider-maas#249]
Hi , 

I have been using Terraform to install k8s cluster on MaAS managed bare metal servers. 
The tooling used for the setup is as followed : 
MaAS - 3.1.3
Terraform - 1.3.9
terraform-provider-maas_v3.1.3 
k8s version - v1.29.6-1.1

The setup was working fine but recently I started hitting this (see logs below) issue. 
Could you please have a look and provide a resolution for the same ?

Let me know if you need any further information. 

01:04:12  │ Error: Plugin did not respond
01:04:12  │ 
01:04:12  │   with maas_instance.maas_k8_worker_instance[2],
01:04:12  │   on main.tf line 158, in resource "maas_instance" "maas_k8_worker_instance":
01:04:12  │  158: resource "maas_instance" "maas_k8_worker_instance" {
01:04:12  │ 
01:04:12  │ The plugin encountered an error, and failed to respond to the
01:04:12  │ plugin.(*GRPCProvider).PlanResourceChange call. The plugin logs may contain
01:04:12  │ more details.
01:04:12  ╵
01:04:12  ╷
01:04:12  │ Error: Plugin did not respond
01:04:12  │ 
01:04:12  │   with maas_instance.maas_k8_worker_instance[1],
01:04:12  │   on main.tf line 158, in resource "maas_instance" "maas_k8_worker_instance":
01:04:12  │  158: resource "maas_instance" "maas_k8_worker_instance" {
01:04:12  │ 
01:04:12  │ The plugin encountered an error, and failed to respond to the
01:04:12  │ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
01:04:12  │ contain more details.
01:04:12  ╵
01:04:12  ╷
01:04:12  │ Error: Plugin did not respond
01:04:12  │ 
01:04:12  │   with maas_instance.maas_k8_worker_instance[0],
01:04:12  │   on main.tf line 158, in resource "maas_instance" "maas_k8_worker_instance":
01:04:12  │  158: resource "maas_instance" "maas_k8_worker_instance" {
01:04:12  │ 
01:04:12  │ The plugin encountered an error, and failed to respond to the
01:04:12  │ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
01:04:12  │ contain more details.
01:04:12  ╵
01:04:12  
01:04:12  Stack trace from the terraform-provider-maas_v3.1.3 plugin:
01:04:12  
01:04:12  panic: interface conversion: interface {} is nil, not string
01:04:12  
01:04:12  goroutine 349 [running]:
01:04:12  main.parseConstraints(0xc0001305b0, 0x1, 0x1, 0x0)
01:04:12  	github.com/roblox/terraform-provider-maas/maas_client.go:228 +0x6c8
01:04:12  main.resourceMAASInstanceCreate(0xc0001305b0, 0xf92160, 0xc000582840, 0x2, 0x1b84d20)
01:04:12  	github.com/roblox/terraform-provider-maas/maas_instance.go:24 +0x8f
01:04:12  github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc000101280, 0xc0000c4410, 0xc000516940, 0xf92160, 0xc000582840, 0xfa0301, 0xc00009b128, 0xc00044baa0)
01:04:12  	github.com/hashicorp/terraform@v0.12.20/helper/schema/resource.go:305 +0x365
01:04:12  github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc000101580, 0xc0006a78a8, 0xc0000c4410, 0xc000516940, 0xc00009b1a8, 0xc00000e080, 0xfa2720)
01:04:12  	github.com/hashicorp/terraform@v0.12.20/helper/schema/provider.go:289 +0x99
01:04:12  github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc0000beaf0, 0x13d05c0, 0xc0005ac030, 0xc0004ae0c0, 0xc0000beaf0, 0xc0005ac030, 0xc0000a1a20)
01:04:12  	github.com/hashicorp/terraform@v0.12.20/helper/plugin/grpc_provider.go:885 +0x8c4
01:04:12  github.com/hashicorp/terraform/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x10c91e0, 0xc0000beaf0, 0x13d05c0, 0xc0005ac030, 0xc0000c4140, 0x0, 0x13d05c0, 0xc0005ac030, 0xc000022800, 0x46d5)
01:04:12  	github.com/hashicorp/terraform@v0.12.20/internal/tfplugin5/tfplugin5.pb.go:3189 +0x217
01:04:12  google.golang.org/grpc.(*Server).processUnaryRPC(0xc00058a600, 0x13dc600, 0xc00058b380, 0xc0005b0900, 0xc000143a70, 0x1b4a160, 0x0, 0x0, 0x0)
01:04:12  	google.golang.org/grpc@v1.21.1/server.go:998 +0x46a
01:04:12  google.golang.org/grpc.(*Server).handleStream(0xc00058a600, 0x13dc600, 0xc00058b380, 0xc0005b0900, 0x0)
01:04:12  	google.golang.org/grpc@v1.21.1/server.go:1278 +0xd3d
01:04:12  google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0000b8390, 0xc00058a600, 0x13dc600, 0xc00058b380, 0xc0005b0900)
01:04:12  	google.golang.org/grpc@v1.21.1/server.go:717 +0xa1
01:04:12  created by google.golang.org/grpc.(*Server).serveStreams.func1
01:04:12  	google.golang.org/grpc@v1.21.1/server.go:715 +0xa1
01:04:12  
01:04:12  Error: The terraform-provider-maas_v3.1.3 plugin crashed!
01:04:12  
01:04:12  This is always indicative of a bug within the plugin. It would be immensely
01:04:12  helpful if you could report the crash with the plugin's maintainers so that it
01:04:12  can be fixed. The output above should help diagnose the issue.

Regards,
Prateek

**Comment by pchandra19** [comment]
On debugging further, just realised that due a recent change from our end ..the tag being passed to worker instance was coming as "" which in my opinion caused the plugin to crash. I am closing the issue.
